### PR TITLE
Update for upstream PR

### PR DESCRIPTION
**Pull request by mmcauliffe**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mmcauliffe** [comment]
@h-vetinari Ok I think I've figured out the issues with getting windows working with netlib, comes down to find_blas not picking up cblas or lapack: https://gitlab.kitware.com/cmake/cmake/-/issues/19381, so I've added an explicit call to link with those.  Also updated some tests to get rid of sgmm and fgmmbin tests, along with updating some CUDA flag detection.  Can you double check and make sure this looks good for your purposes?

**Comment by h-vetinari** [comment]
Hey @mmcauliffe 

Thanks for picking this up. 4h isn't really a lot of time for a response (I'm in a different timezone too), and I think that it would have been cleaner to base your changes onto #25 (as quite a bit of work went into that, and it's good practice to keep that history as well as attribution), but overall I'm very happy that this is finally done. :)

**Comment by h-vetinari** [comment]
Ah, and I just noticed that you switched off `BUILD_SHARED_LIBS` on windows - that was definitely not the intention of #25.

**Comment by h-vetinari** [comment]
Since you picked up my changes inconsistently (missing the `feedstock-name: kaldi` change**), the test section for `kaldi` most likely did not run completely.

** it's an unfortunate bug/side-effect of conda-build that having an output with the same name as the package will not correctly run the test section of that output.

**Comment by h-vetinari** [comment]
> Since you picked up my changes inconsistently (missing the `feedstock-name: kaldi` change**), the test section for `kaldi` most likely did not run completely.

Even though `run_test.py` was executed, the `commands:` section seems to have gotten skipped. For example, since we're not building shared libraries on windows, the following line would have had to fail but didn't:
```
- if not exist %LIBRARY_BIN%\kaldi-{{ each_lib }}.dll exit 1   # [win]
```

**Pull request merged**
