### PR TITLE
Add kaldi_libs python package for egs/wsj/s5/steps/libs package

### PR DESCRIPTION
**Pull request by mmcauliffe**
Increment kaldi version

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mmcauliffe** [comment]
@h-vetinari this should be good to go.  I discovered when diving into some kaldi nnet3 that they had a python library squirreled away in the egs folder that a lot of the nnet3 functionality depends on, so I've added that as part of the installation (with the name changed from "libs" to "kaldi_libs".

The build matrix is getting pretty large with cuda versions and python versions now.  I did see that pytorch was considering only supporting cuda 11.2+, maybe a similar route would be good here too (as a another PR once they settle on the issue).

**Comment by h-vetinari** [comment]
> I discovered when diving into some kaldi nnet3 that they had a python library squirreled away in the egs folder that a lot of the nnet3 functionality depends on, so I've added that as part of the installation (with the name changed from "libs" to "kaldi_libs".

So this is about python bindings to the libs, correct?

I've been low on FOSS time recently, but one of my plans has been to have an `output:` called libkaldi that just has the headers and shared libs without the python stuff (this is what I'd need ideally for torchaudio).

Just checking that this is not somehow related. In any case, `kaldi_libs` is not my favourite name tbh... It's too generic, contains an underscore, etc. IIUC this is only used internally? If so, can we name it with a leading underscore (so that people don't start depending on a quirk of our packaging), something like `_pykaldi`?

**Comment by mmcauliffe** [comment]
> So this is about python bindings to the libs, correct?


So they're not bindings, they're helper functions for various kaldi scripts, particularly parsing an "xconfig" file format and setting up nnet3 layers and training functions. I'm still a bit on the fence about it too, because it seems like it's called from scripts to generate text files specifying the network architecture and training parameters.  But the other route for me would be to basically duplicate a lot of this code for my own purposes, because the nnet3 binaries depend on files in this format. 

> I've been low on FOSS time recently, but one of my plans has been to have an `output:` called libkaldi that just has the headers and shared libs without the python stuff (this is what I'd need ideally for torchaudio).

No worries, I have also been low on it too lately.  This should be independent of that effort, since torchaudio since none of these would be necessary for any pytorch networks.  All that's really necessary for torchaudio is Kaldi's IO libraries right? 

> Just checking that this is not somehow related. In any case, `kaldi_libs` is not my favourite name tbh... It's too generic, contains an underscore, etc. IIUC this is only used internally? If so, can we name it with a leading underscore (so that people don't start depending on a quirk of our packaging), something like `_pykaldi`?

 I'm hesitant on `_pykaldi` as there is another package named [pykaldi](https://github.com/pykaldi/pykaldi).  Would something like `kaldinnet3` (with or without the leading underscore) be ok? Maybe some variant on `kaldipy` or `kalpy` that doesn't get too close to the existing pykaldi?  The package does have some generic common functionality for working with kaldi file types, but most of it seems to be dedicated to nnet3: https://github.com/kaldi-asr/kaldi/tree/master/egs/wsj/s5/steps/libs.

Looking at pykaldi a bit more, they might already be covering these features as they're a proper python binding, so maybe it'd be worth getting it on conda forge as an alternate path but that might also be more effort.

**Comment by h-vetinari** [comment]
> I discovered when diving into some kaldi nnet3 that they had a python library squirreled away in the egs folder that a lot of the nnet3 functionality depends on, so I've added that as part of the installation (with the name changed from "libs" to "kaldi_libs".

So this is about python bindings to the libs, correct?

I've been low on FOSS time recently, but one of my plans has been to have an `output:` called libkaldi that just has the headers and shared libs without the python stuff (this is what I'd need ideally for torchaudio).

Just checking that this is not somehow related. In any case, `kaldi_libs` is not my favourite name tbh... It's too generic, contains an underscore, etc. IIUC this is only used internally? If so, can we name it with a leading underscore (so that people don't start depending on a quirk of our packaging), something like `_pykaldi`?

> Looking at pykaldi a bit more, they might already be covering these features as they're a proper python binding, so maybe it'd be worth getting it on conda forge as an alternate path but that might also be more effort.

I saw you've been following up on that, thanks a lot! :)

**Comment by mmcauliffe** [comment]
Yep, the pykaldi compatibility patch is working now, so this should be good to merge. I'm hoping that most or all of it can be merged in upstream, but for the moment I can use this to get a pykaldi feedstock working.

None of the changes should affect any components necessary for torchaudio integration, since the changes just add functions for pykaldi operations (functions returning pointers and "move assignment", not too sure what that is), so all the existing functionality upstream should be unchanged.

**Comment by mmcauliffe** [comment]
@h-vetinari sorry for the ping, but any objections on your end for merging this?

**Comment by h-vetinari** [comment]
> @h-vetinari sorry for the ping, but any objections on your end for merging this?

Hey, thanks for the ping, and sorry for the slow response. Haven't been able to dig through all my pings after a long move yet.

**Comment by h-vetinari** [comment]
A 2800 line patch is really hard to review. Could you describe what this patch (resp. this PR) does in a few sentences?

What I'm mostly interested in: does the patch change anything observable about how (non-python) kaldi works?

Beyond that, I remember a notification where you [said](https://github.com/pykaldi/pykaldi/issues/307#issuecomment-1281439920) you'd try to upstream this? Could we try that before we push merge here? Maybe get some potential issues with the patch sorted out through the upstream maintainers?

**Comment by mmcauliffe** [comment]
Ok, so I was trying to get pykaldi set up offline to see if it was worth the effort of upstreaming this and getting PyKaldi as a staged recipe, but it looks like it'll be a bit of a headache.  PyKaldi requires CLIF (https://github.com/google/clif), which I don't think is on conda forge, and it looks from my day of looking into it that it gets compiled as part of compiling LLVM (and specifically 11.X or whatever), and then that took me into stacks that I really don't know what's going on.

I think for my purposes trying to do speech-based DNN, I'll look more into depending on SpeechBrain or PyTorch directly, and just skip any Kaldi nnet integration. It's a shame though that PyTorch GPU is only available for linux builds (I did see your issue almost two years ago: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32).  It's a shame that support is so fragmented.

For the purposes of this, I'll remove the pykaldi patch/close this PR, but not much has changed upstream since the last release, so probably not worth just a version bump.

**Comment by h-vetinari** [comment]
> PyKaldi requires CLIF (https://github.com/google/clif)

I think we could try to get that done nevertheless.

> It's a shame though that PyTorch GPU is only available for linux builds (I did see your issue almost two years ago: [conda-forge/pytorch-cpu-feedstock#32](https://github.com/conda-forge/pytorch-cpu-feedstock/issues/32)).

It's hard to pull off without someone paying for beefier CI, though people are working on that...

> For the purposes of this, I'll remove the pykaldi patch/close this PR

Unless open PRs bother you, I think we should leave it open. The work is still valuable and once the other pieces get moved into place eventually, we could revisit.

**Comment by mmcauliffe** [comment]
I don't think this is necessary with [kalpy being available on conda forge](https://github.com/conda-forge/kalpy-feedstock/) now.

**Pull request closed without merging**
